import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Search from "./components/search";
import LayoutProfileMngmnt from "./components/layout-profile-mngmnt";
import Link from "next/link";
import Image from "next/image";
import logo from "@/public/logo.png";
import { validateRequest } from "./lib/auth";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LetterJoexd",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await validateRequest();

  return (
    <html lang="en">
      <body className={`${inter.className} min-h-[100vh] flex flex-col`}>
        <header className="flex flex-col gap-4 sm:flex-row content-center p-4 bg-slate-100">
          <div className="flex flex-row gap-4">
            <Link
              href={"/"}
              className="font-bold text-3xl w-min text-center leading-normal"
            >
              LetterJoexd
            </Link>
            <Image
              src={logo}
              alt="Picture of the poster"
              priority={true}
              width={90}
              height={25}
            />
          </div>

          <Search />
          <LayoutProfileMngmnt user={user} />
          <Toaster position="top-right" />
        </header>
        <main className="p-4 pb-8 flex-1">{children}</main>
        <footer className="bg-slate-100 p-6 flex justify-center text-sm text-slate-400">
          <p>
            Built thanks to the{" "}
            <Link
              href={"https://developer.themoviedb.org/docs/getting-started"}
              target="_blank"
              className="underline-offset-1 underline"
            >
              TMDB API.
            </Link>
          </p>
        </footer>
      </body>
    </html>
  );
}
