import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Search from "./search";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={(inter.className, "p-8")}>
        <header className="flex flex-row content-center">
          <h1 className="pr-10 font-bold text-2xl">LetterJoexd</h1>
          <Search />
        </header>
        <main className="pt-8">{children}</main>
      </body>
    </html>
  );
}
